---
- name: install docker
  hosts: server
  become: true
  tasks:
    - name: install dependencies
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: get gpg key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: add docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: install docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io

    # makesure docker follow ufw
    - name: Check if /etc/docker/daemon.json file exists
      stat:
        path: /etc/docker/daemon.json
      register: daemon_json_file

    - name: Ensure daemon.json file exists
      copy:
        dest: /etc/docker/daemon.json
        content: ""
        mode: "0644"
        owner: root
        group: root
      when: not daemon_json_file.stat.exists

    - name: Configure daemon.json for follow ufw rule
      blockinfile:
        path: /etc/docker/daemon.json
        block: |
          { 
            "iptables" : false 
          }

    - name: start service
      service:
        name: docker
        state: started
        enabled: true

  handlers:
    - name: restart docker
      service:
        name: docker
        state: restarted
